{% set name = "domb-napari" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/domb_napari-{{ version }}.tar.gz
  sha256: 6b1a6f1b366861b2a512ddd0e8aeb1b8ddf25a32a1c83d0022a1e4f03118ef30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - dipy
    - domb
    - matplotlib-base
    - napari
    - numpy
    - plotly
    - python >=3.8
    - scikit-image
    - scipy
    - vispy

test:
  imports:
    - domb_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/domb-napari
  summary: Napari plugin implementing DoMB Tools for analyzing fluorescence-labeled proteins redistribution
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/wisstock/domb-napari

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - wisstock
